default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dev
  password: dev
  host: localhost

development:
  <<: *default
  database: promulgation_development

test:
  <<: *default
  database: promulgation_test

production:
  <<: *default
  database: promulgation_production
  username: promulgation
  password: <%= ENV['PROMULGATION_DATABASE_PASSWORD'] %>
